# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
name: "beats-xpack-packetbeat"

env:
  AWS_ARM_INSTANCE_TYPE: "m6g.xlarge"
  AWS_IMAGE_UBUNTU_ARM_64: "platform-ingest-beats-ubuntu-2204-aarch64"

  GCP_DEFAULT_MACHINE_TYPE: "c2d-highcpu-8"
  GCP_HI_PERF_MACHINE_TYPE: "c2d-highcpu-16"
  GCP_WIN_MACHINE_TYPE: "n2-standard-8"

  IMAGE_RHEL9_X86_64: "family/platform-ingest-beats-rhel-9"
  IMAGE_UBUNTU_X86_64: "family/platform-ingest-beats-ubuntu-2204"
  IMAGE_WIN_10: "family/platform-ingest-beats-windows-10"
  IMAGE_WIN_11: "family/platform-ingest-beats-windows-11"
  IMAGE_WIN_2016: "family/platform-ingest-beats-windows-2016"
  IMAGE_WIN_2019: "family/platform-ingest-beats-windows-2019"
  IMAGE_WIN_2022: "family/platform-ingest-beats-windows-2022"
  IMAGE_WIN_2025: "family/platform-ingest-beats-windows-2025"

  IMAGE_BEATS_WITH_HOOKS_LATEST: "docker.elastic.co/ci-agent-images/platform-ingest/buildkite-agent-beats-ci-with-hooks:latest"

  #Deps
  ASDF_MAGE_VERSION: 1.15.0

  # Unit tests
  RACE_DETECTOR: "true"
  TEST_COVERAGE: "true"

  # Concurrency definition
  CONCURRENCY_GROUP: "orka-concurrency-group"
  CONCURRENCY_COUNT: 10
  CONCURRENCY_METHOD: eager

steps:
  - group: "Mandatory Tests"
    key: "x-pack-packetbeat-mandatory-tests"

    steps:

      - label: ":windows: x-pack/packetbeat: Win 2022 System Tests"
        key: "mandatory-win-2022-system-tests"
        command: |
          Set-Location -Path x-pack/packetbeat
          mage systemTest
        retry:
          automatic:
            - limit: 1
        agents:
          provider: "gcp"
          image: "${IMAGE_WIN_2022}"
          machineType: "${GCP_WIN_MACHINE_TYPE}"
          disk_size: 100
          disk_type: "pd-ssd"
        artifact_paths:
          - "x-pack/packetbeat/build/*.xml"
          - "x-pack/packetbeat/build/*.json"
        plugins:
          - test-collector#v1.10.2:
              files: "x-pack/packetbeat/build/TEST-*.xml"
              format: "junit"
              branches: "main"
              debug: true
          # See https://github.com/elastic/oblt-infra/blob/main/conf/resources/repos/beats/01-gcp-buildkite-oidc.tf
          # This plugin authenticates to Google Cloud using the OIDC token.
          - elastic/oblt-google-auth#v1.2.0:
              lifetime: 10800 # seconds
              project-id: "elastic-observability-ci"
              project-number: "911195782929"
        notify:
          - github_commit_status:
              context: "x-pack/packetbeat: Win 2022 System Tests"

      - label: ":windows: x-pack/packetbeat: Win 2025 System Tests"
        key: "mandatory-win-2025-system-tests"
        command: |
          Set-Location -Path x-pack/packetbeat
          mage systemTest
        retry:
          automatic:
            - limit: 1
        agents:
          provider: "gcp"
          image: "${IMAGE_WIN_2025}"
          machineType: "${GCP_WIN_MACHINE_TYPE}"
          disk_size: 100
          disk_type: "pd-ssd"
        artifact_paths:
          - "x-pack/packetbeat/build/*.xml"
          - "x-pack/packetbeat/build/*.json"
        plugins:
          - test-collector#v1.10.2:
              files: "x-pack/packetbeat/build/TEST-*.xml"
              format: "junit"
              branches: "main"
              debug: true
          # See https://github.com/elastic/oblt-infra/blob/main/conf/resources/repos/beats/01-gcp-buildkite-oidc.tf
          # This plugin authenticates to Google Cloud using the OIDC token.
          - elastic/oblt-google-auth#v1.2.0:
              lifetime: 10800 # seconds
              project-id: "elastic-observability-ci"
              project-number: "911195782929"
        notify:
          - github_commit_status:
              context: "x-pack/packetbeat: Win 2025 System Tests"

      - label: ":windows: x-pack/packetbeat: Win 10 System Tests"
        key: "extended-win-10-system-tests"
        command: |
          Set-Location -Path x-pack/packetbeat
          mage systemTest
        retry:
          automatic:
            - limit: 1
        agents:
          provider: "gcp"
          image: "${IMAGE_WIN_10}"
          machineType: "${GCP_WIN_MACHINE_TYPE}"
          disk_size: 100
          disk_type: "pd-ssd"
        artifact_paths:
          - "x-pack/packetbeat/build/*.xml"
          - "x-pack/packetbeat/build/*.json"
        plugins:
          - test-collector#v1.10.2:
              files: "x-pack/packetbeat/build/TEST-*.xml"
              format: "junit"
              branches: "main"
              debug: true
          # See https://github.com/elastic/oblt-infra/blob/main/conf/resources/repos/beats/01-gcp-buildkite-oidc.tf
          # This plugin authenticates to Google Cloud using the OIDC token.
          - elastic/oblt-google-auth#v1.2.0:
              lifetime: 10800 # seconds
              project-id: "elastic-observability-ci"
              project-number: "911195782929"
        notify:
          - github_commit_status:
              context: "x-pack/packetbeat: Win 10 System Tests"
