# input
filebeat.inputs:
  - type: filestream
    id: local-jsonloggenerator
    enabled: true
    paths:
      - /Users/zhangning37/project-go/beats/a_cqdxzn_tools/jsonloggenerator/logs/jsonloggenerator*.log
    #exclude_lines: ['^0']
    #include_lines: ['^ERR','^WARN']
    fields:
      source-code: golang
      app: jsonloggenerator

# setup
setup:
  template:
    enabled: true
    type: index
    name: local-jsonloggenerator-template # update
    pattern: demo-*
    settings:
      index:
        number_of_shards: 1
        number_of_replicas: 1
  ilm:
    enabled: true
    policy_name: cqdxzn-local-demo-policy   # lifecycle policy name
    rollover_alias: local-jsonloggenerator
    pattern: "{now/d}-0001"
    check_exists: true
    overwrite: false
  kibana:

# output
output.elasticsearch:
  hosts: ["localhost:9200"]
  protocol: "http"
  username: "elastic"
  password: "elastic"

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

logging.level: info
